### ISSUE TITLE
Basket Trading Constituent UI fixes

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1005]
1. Update is being applied to incorrect column sometime

![Image](https://github.com/finos/vuu/assets/148964225/cf094672-4581-44bc-a609-ef665cae881c)

![Image](https://github.com/finos/vuu/assets/148964225/56128868-9a28-49bb-af3c-4ef91c5c9607)

2. When  you edit cell and hit enter, it skips a row rather than going to next row 
3. Basket Trading Constituent currently allow row to be dragged and dropped which ends up with some rows end up being stuck as a floating row that stays while you scroll - should disable the drag and drop 

![Image](https://github.com/finos/vuu/assets/148964225/3edd54ad-d76b-491d-b4da-a9be60cb2dfc)

4. Quantity needs to be read only column as it is always calculated on the server side
```[tasklist]
### Tasks
- [ ] 1
- [x] 2 on blur of editable cell, do not commit if dirty flag not set
- [x] 3 do not allow dragStart on a drop-only table
- [x] 4 remove editable from Qty column
```
