### ISSUE TITLE
Create Fully featured Instrument Prices Tile Feature

### ISSUE THREAD

**Issue by heswell** [finos/vuu#1038]
Codebase currently contains an Instrument Tiles feature. This is a bare-bones implementation, missing a lot of functionality.

We need the following features to make this a useful and re-usable component.

- Tiled Layout Container
- Tile implementation
- Instrument Picker to populate component
- Density selector 
- Toolbar to host instrument picker and density selector

Each of these will be the subject of individual issues

```[tasklist]
### Tasks
- [ ] https://github.com/finos/vuu/issues/952
- [ ] https://github.com/finos/vuu/issues/1039
- [ ] https://github.com/finos/vuu/issues/1040
- [ ] https://github.com/finos/vuu/issues/1041
- [ ] https://github.com/finos/vuu/issues/1050
```
