### ISSUE TITLE
EPIC Improve Date Presentation in UI

### ISSUE THREAD

**Issue by heswell** [finos/vuu#1071]
Columns with date, time or datetime values are sent to ui as unix timestamp values , with the data type `long`. The UI currently renders these as numbers.

Eventually, we want to support more descriptive metadata  for such fields, so the UI can make more sensible choices for formatting such fields. 

In any case, we need to support  well formatted date and time values. FIrst step is to support this via explicit configuration (on the column config i.e ColumnDescriptor)
Once this is in place, we can expose this functionality on the ColumnSettings panel, so users can adjust date time formatting in the same way that they can choose formatting settings for numeric data.
Finally, we can extend the functionality of filtering, so that columns marked by user (and eventually by server) as date ot time values, can offer date specicif filtering UI.

```[tasklist]
### Tasks
- [ ] https://github.com/finos/vuu/issues/1072
- [ ] https://github.com/finos/vuu/issues/1073
- [ ] https://github.com/finos/vuu/issues/1074
```
