### ISSUE TITLE
EPIC full theming support for Vuu UI components

### ISSUE THREAD

**Issue by heswell** [finos/vuu#1209]
Vuu UI components should consume CSS attribute values from theme variables. Once done, theme can be switched and all components will be styled correctly from the current theme, including both light/dark mode and density support.

Vuu theme should be updated where necessary to provide correct characteristic variables for components.

For each of the tasks below, we need to
- create an example that shows components in all available states, e.g for a Button, active, focused, disabled etc
- ensure that the components look correct with Salt theme applied, in all densities and for both light and dark
- update Vuu theme so that components match Vuu designs 

- [ ] Update Showcase to include light/dark toggle and ToggleButtonGroup for density
- [ ] Update Salt dependencies to latest versions
- [ ] Create Showcase theming examples for Salt Button, Input, Checkbox, RadioButton ToggleButton 
- [ ] Create Showcase theming example for SplitButton, Dropdown, Combobox
- [ ] Create Showcase theming example for FilterBar
- [ ] Create Showcase theming example for Table
- [ ] Create Showcase theming example for Vuu Layout components
