### ISSUE TITLE
Usages of View Port and DataTable need to be clearly separated

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1412]
### Discussed in https://github.com/finos/vuu/discussions/1368

Support hidding some columns by specifying subset of the table columns in view port def function
& filter on display values (i.e. view port data) 

```[tasklist]
### Tasks
- [ ] https://github.com/finos/vuu/issues/1415
- [ ] https://github.com/finos/vuu/issues/1468
- [ ] https://github.com/finos/vuu/issues/1434
- [ ] Review usages of getting row data and ensure ViewPort data vs Table data is used in correct cases
```

**Comment by naleeha** [comment]
done, moving 1468 to backlog to be tackled another time
